let x: number = 5;
let y: number = 8;
console.log('Equal:', x == y);
console.log('Not equal:', x != y);
console.log('Greater than:', x > y);
console.log('Less than:', x < y);
let isAdult: boolean = true;
let hasDrivingLicense: boolean = false;
console.log('AND logical:', isAdult && hasDrivingLicense);
console.log('OR logical:', isAdult || hasDrivingLicense);